### ISSUE TITLE
delayed and untimely packet posts

### ISSUE THREAD

**Issue by lccreech** [daniestevez/gr-outernet#3]
Daniel,
outernet-rtlsdr.grc had been running for some time, a long time which is unusual for me and not getting hung up. When I noticed this today from free-outernet. Its not  a free outernet-problem but a outernet-rtlsdr.grc issue. Restarting free-outernet still had the old, very old time stamps.. I wasn't till restarting outernet-rtlsdr.grc that it was resolved, this data was seconds apart from restarting the grc model:

Unsupported fragment type: d6
Receiving Ethernet frames from groundstation with MAC 00:30:18:c1:dc:a8
[Time service] Server ID: odc2
[Time service] Server time: 2017-05-08 19:13:57 UTC
[Time service] Server ID: odc2
[Time service] Server time: 2017-05-08 19:14:57 UTC
[Time service] Server ID: odc2
[Time service] Server time: 2017-05-08 19:15:57 UTC
[Time service] Server ID: odc2
**[Time service] Server time: 2017-05-08 19:16:57 UTC**
Traceback (most recent call last):
  File "./free-outernet.py", line 167, in <module>
    main()
  File "./free-outernet.py", line 164, in main
    processFrame(frame)
  File "./free-outernet.py", line 64, in processFrame
    packet = opDefragmenter.push(protocols.OP(frame[14:]))
  File "/home/larry/Downloads/free-outernet/protocols.py", line 176, in push
    decoded = ldp.decode()
  File "/home/larry/Downloads/free-outernet/protocols.py", line 123, in decode
    return b''.join(decoder.decode([self.__fragments[s] for s in sharenums], sharenums))
_fec.Error: Precondition violation: Wrong length -- first argument is required to contain exactly k blocks.  len(first): 7, k: 6
[larry@localhost free-outernet]$ export PYTHONPATH="/usr/lib64/python3.4/site-packages"^C
[larry@localhost free-outernet]$ ^C
[larry@localhost free-outernet]$ python3 ./free-outernet.py 
Receiving Ethernet frames from groundstation with MAC 00:30:18:c1:dc:a8
[Time service] Server ID: odc2
[Time service] Server time: 2017-05-23 03:36:00 UTC
[Time service] Server ID: odc2
[Time service] Server time: 2017-05-23 03:37:00 UTC
[Time service] Server ID: odc2
[Time service] Server time: 2017-05-23 03:38:00 UTC
[Time service] Server ID: odc2

**Comment by daniestevez** [comment]
I don't know what to make of this. It is weird.

First off: are you running the latest free-outernet version? The crash you're seeing is supposed to be fixed in b5b4c7b1facf97b1e846644856f41dd25a693402

Second: The timestamps come from the packets broadcast by outernet. I find it very unlikely that a bug in free-outernet would cause incorrect timestamps to be printed. Most likely the Outernet groundstation had the date and time incorrectly set and it was broadcasting incorrect timestamps. The packets are checksumed, so it is very unlikely that a bug in the receiver would get incorrect timestamps but be happy about the checksum.

**Comment by lccreech** [comment]
I  don't think it's free outernet. I had started and restarted it and it still had bad time stamps. It wasn't until I restarted my outernet.grc that it corrected.
